workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_292.jdk/Contents/Home
        ANDROID_SDK_ROOT: /Users/builder/Library/Android/sdk
    scripts:
      - name: Accept Licenses
        script: |
          yes | sdkmanager --licenses
      - name: Set up Android SDK
        script: |
          sdkmanager "platforms;android-30" "build-tools;30.0.3"
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
