workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      android:
        api_level: 30
        build_tools_version: 30.0.3
      java:
        version: 8
    scripts:
      - name: Accept Licenses
        script: |
          yes | sdkmanager --licenses
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
