workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /opt/android-sdk-linux
    scripts:
      - name: Set up Android SDK
        script: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3"
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
